### ISSUE TITLE
(Info): Introduction and Terminologies

### ISSUE THREAD

**Issue by aayu5hgit** [aayu5hgit/histograde#1]
@MansiBellani @anujbagad 
Here, we'll be discussing various **terminologies** and the **introductory part** of the project to ease the level of understanding.
Let's begin with understanding the concept of **Histopathology** and terms related to it.

`Histopathology` is the study of tissues at a microscopic level. It involves examining thin slices of tissue, usually obtained through biopsies or surgical procedures, under a microscope. This helps pathologists (doctors who specialize in studying diseases) to identify any abnormal changes in the cells, their organization, and their overall structure.

**Tradtitional Process:** 
`Sample Collection → Processing → Microscopic Examination → Microscopic Analysis → Diagnosis → Report`

When we talk about `Histopathological Cancer`, we are referring to the process of **analyzing tissue samples** to determine if cancer is present, what type of cancer it is, how aggressive it might be, and other important characteristics. In addition, histopathological analysis of cancerous tissues is a meticulous process that provides crucial information about the type, grade, and stage of cancer.

**Comment by anujbagad** [comment]
Hematoxylin: This is a blue-purple color. It's used to highlight the nuclei of cells. Nuclei are like the control centers of cells, containing their genetic information.

Eosin: This is a pinkish color. It's used to show the other parts of cells and tissues, like the cytoplasm. Cytoplasm is like the jelly-like material that surrounds the nucleus in a cell.
